name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install -r requirements.txt
          pip install coverage
        working-directory: ./gre
      
      - name: Run tests with coverage
      #同層級順序不影響運行
        working-directory: ./gre
        run: |
          venv\Scripts\activate
          coverage run manage.py test
          coverage report
