name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: ./gre

      - name: Run tests
        working-directory: ./gre
        run: |
          source venv/bin/activate
          python manage.py test

  



      
      

